[package]
name = "rot8"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0.57"
env_logger = "^0.9.0"
clap = { version = "^3.1.18", features = ["derive"] }
log = "^0.4.17"
pixels = "^0.9.0"
winit = "^0.26.1"
winit_input_helper = "^0.12.0"
rotlib = { path = "../rotlib" }
