on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: lint

env:
  SKIP: no-commit-to-branch

jobs:
  lint:
    name: r8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install alsa
        run: sudo apt-get install libasound2-dev
      - name: setup python
        uses: actions/setup-python@v3
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run pre-commit hooks
        uses: pre-commit/action@v3.0.0
