on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: lint

jobs:
  lint:
    name: r8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: pre-commit/action@v3.0.0
