on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: test

jobs:
  lint:
    name: r8
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install alsa
        run: sudo apt-get install libasound2-dev
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --bins --tests --all-features
      - name: run cargo doc test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
